import type { AppStateData } from "./types";

const now = Date.now();
const hours = (h: number) => new Date(now - h * 3600_000).toISOString();
const days = (d: number) => new Date(now - d * 86400_000).toISOString();
const ahead = (h: number) => new Date(now + h * 3600_000).toISOString();
const aheadDays = (d: number) => new Date(now + d * 86400_000).toISOString();

function msg(
  id: string,
  threadId: string,
  from: string,
  fromName: string,
  subject: string,
  bodyHtml: string,
  sentAt: string,
  extras: Partial<{
    trackersBlocked: string[];
    attachments: AppStateData["messages"][string]["attachments"];
    isOutgoing: boolean;
    to: string[];
  }> = {},
) {
  return {
    id,
    threadId,
    from,
    fromName,
    to: extras.to ?? ["you@hey.local"],
    cc: [] as string[],
    subject,
    bodyHtml,
    bodyText: bodyHtml.replace(/<[^>]+>/g, " "),
    sentAt,
    attachments: extras.attachments ?? [],
    trackersBlocked: extras.trackersBlocked ?? [],
    isOutgoing: extras.isOutgoing,
  };
}

export function createSeed(): AppStateData {
  const messages: AppStateData["messages"] = {
    m1: msg(
      "m1",
      "t1",
      "maya@design.co",
      "Maya Chen",
      "Design review Thursday?",
      `<p>Hey — can we do a quick design review Thursday afternoon? I want your eyes on the new onboarding flow before we ship.</p><p>Also attaching the latest mockups.</p>`,
      hours(2),
      {
        attachments: [
          {
            id: "a1",
            name: "onboarding-v3.fig",
            size: 2_400_000,
            mimeType: "application/octet-stream",
            messageId: "m1",
            threadId: "t1",
            receivedAt: hours(2),
          },
        ],
      },
    ),
    m1b: msg(
      "m1b",
      "t1",
      "you@hey.local",
      "You",
      "Re: Design review Thursday?",
      `<p>Thursday 2pm works for me. I'll bring notes from last week's usability sessions.</p>`,
      hours(1.5),
      { isOutgoing: true },
    ),
    m2: msg(
      "m2",
      "t2",
      "sam@acme.io",
      "Sam Rivera",
      "Contract countersigned",
      `<p>All set — countersigned and attached. Excited to get started Monday.</p>`,
      hours(5),
      {
        attachments: [
          {
            id: "a2",
            name: "MSA-signed.pdf",
            size: 420_000,
            mimeType: "application/pdf",
            messageId: "m2",
            threadId: "t2",
            receivedAt: hours(5),
          },
        ],
      },
    ),
    m3: msg(
      "m3",
      "t3",
      "jordan@family.com",
      "Jordan Lee",
      "Dinner Sunday?",
      `<p>Want to do dinner Sunday? That new place on 5th just opened and I snagged a reservation for 7.</p>`,
      hours(8),
    ),
    m4: msg(
      "m4",
      "t4",
      "newsletter@stratechery.com",
      "Stratechery",
      "The Aggregation Theory Update",
      `<h2>This week in tech strategy</h2><p>Platforms continue to consolidate distribution while creators fight for margin. Here's what changed…</p><p>Read the full analysis below — including three scenarios for AI wrappers in 2026.</p>`,
      hours(10),
      { trackersBlocked: ["open-pixel.stratechery.track"] },
    ),
    m5: msg(
      "m5",
      "t5",
      "digest@morningbrew.com",
      "Morning Brew",
      "Markets, memes, and Monday",
      `<p><strong>Good morning.</strong> Equities opened mixed, coffee futures are weird again, and someone launched another AI calendar.</p><ul><li>Fed watch</li><li>Startup of the week</li><li>Chart of the day</li></ul>`,
      days(1),
    ),
    m6: msg(
      "m6",
      "t6",
      "receipts@amazon.com",
      "Amazon",
      "Your order has shipped",
      `<p>Order <strong>#112-88421</strong> shipped via UPS. Estimated delivery: Wednesday.</p><p>Items: Mechanical keyboard, USB-C hub.</p>`,
      hours(12),
    ),
    m7: msg(
      "m7",
      "t7",
      "noreply@uber.com",
      "Uber",
      "Your Tuesday trip with Uber",
      `<p>Thanks for riding. Total: <strong>$18.40</strong>. Pickup: Market St → Dropoff: Folsom St.</p>`,
      days(1),
    ),
    m8: msg(
      "m8",
      "t8",
      "unknown@coldmail.io",
      "Alex Pitch",
      "Quick question about your stack",
      `<p>Hi — saw your talk and wanted to share our observability platform. Free trial?</p>`,
      hours(3),
      { trackersBlocked: ["trk.coldmail.io/pixel.gif"] },
    ),
    m9: msg(
      "m9",
      "t9",
      "vendor@booth.com",
      "Riley Booth",
      "SPEAKEASY conference follow-up",
      `<p>Great meeting you at the conference. Here's the one-pager we discussed. Looking forward to chatting!</p>`,
      hours(4),
    ),
    m10: msg(
      "m10",
      "t10",
      "hr@acme.io",
      "Acme HR",
      "Benefits enrollment reminder",
      `<p>Open enrollment closes Friday. Please confirm your elections in the portal.</p>`,
      days(2),
    ),
    m11: msg(
      "m11",
      "t11",
      "priya@studio.dev",
      "Priya Nair",
      "Launch checklist",
      `<p>Can you confirm the final copy for the pricing page? Blocking the deploy.</p><p>Phone if easier: <strong>415-555-0142</strong></p>`,
      hours(6),
    ),
    m12: msg(
      "m12",
      "t12",
      "billing@github.com",
      "GitHub",
      "Payment receipt for GitHub Team",
      `<p>We charged $44.00 for GitHub Team. Invoice attached for your records.</p>`,
      days(3),
      {
        attachments: [
          {
            id: "a3",
            name: "invoice-march.pdf",
            size: 88_000,
            mimeType: "application/pdf",
            messageId: "m12",
            threadId: "t12",
            receivedAt: days(3),
          },
        ],
      },
    ),
    m13: msg(
      "m13",
      "t13",
      "notifications@slack.com",
      "Slack",
      "You have 14 unread messages",
      `<p>Catch up in #product and #design when you have a minute.</p>`,
      hours(1),
    ),
    m14: msg(
      "m14",
      "t14",
      "notifications@slack.com",
      "Slack",
      "Reminder: standup in 10 minutes",
      `<p>Daily standup starts soon in #standup.</p>`,
      hours(0.5),
    ),
    m15: msg(
      "m15",
      "t15",
      "spam@prize-now.biz",
      "Prize Desk",
      "You've been selected!!!",
      `<p>Claim your prize within 24 hours.</p>`,
      hours(0.2),
      { trackersBlocked: ["spy.prize-now.biz"] },
    ),
  };

  return {
    messages,
    threads: [
      {
        id: "t1",
        subject: "Design review Thursday?",
        box: "lesbox",
        contactEmail: "maya@design.co",
        contactName: "Maya Chen",
        messageIds: ["m1", "m1b"],
        seen: false,
        replyLater: false,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [{ id: "sn1", text: "Bring usability notes + Figma comments", createdAt: hours(1) }],
        privateNotes: [],
        collectionIds: ["col1"],
        workflowId: "wf1",
        workflowStageId: "ws2",
        notify: true,
        shareToken: "share_design_review",
        accountMark: "work",
        createdAt: hours(2),
        updatedAt: hours(1.5),
      },
      {
        id: "t2",
        subject: "Contract countersigned",
        box: "lesbox",
        contactEmail: "sam@acme.io",
        contactName: "Sam Rivera",
        messageIds: ["m2"],
        seen: false,
        replyLater: true,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [{ id: "pn1", text: "Kickoff Monday 10am — send agenda Sunday night.", files: [], createdAt: hours(4) }],
        collectionIds: ["col1"],
        workflowId: "wf1",
        workflowStageId: "ws3",
        notify: false,
        accountMark: "work",
        createdAt: hours(5),
        updatedAt: hours(5),
      },
      {
        id: "t3",
        subject: "Dinner Sunday?",
        box: "lesbox",
        contactEmail: "jordan@family.com",
        contactName: "Jordan Lee",
        messageIds: ["m3"],
        seen: true,
        replyLater: false,
        setAside: true,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        accountMark: "personal",
        createdAt: hours(8),
        updatedAt: hours(8),
      },
      {
        id: "t4",
        subject: "The Aggregation Theory Update",
        box: "feed",
        contactEmail: "newsletter@stratechery.com",
        contactName: "Stratechery",
        messageIds: ["m4"],
        seen: false,
        replyLater: false,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        createdAt: hours(10),
        updatedAt: hours(10),
      },
      {
        id: "t5",
        subject: "Markets, memes, and Monday",
        box: "feed",
        contactEmail: "digest@morningbrew.com",
        contactName: "Morning Brew",
        messageIds: ["m5"],
        seen: true,
        replyLater: false,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        createdAt: days(1),
        updatedAt: days(1),
      },
      {
        id: "t6",
        subject: "Your order has shipped",
        box: "paper_trail",
        contactEmail: "receipts@amazon.com",
        contactName: "Amazon",
        messageIds: ["m6"],
        seen: false,
        replyLater: false,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        createdAt: hours(12),
        updatedAt: hours(12),
      },
      {
        id: "t7",
        subject: "Your Tuesday trip with Uber",
        box: "paper_trail",
        contactEmail: "noreply@uber.com",
        contactName: "Uber",
        messageIds: ["m7"],
        seen: true,
        replyLater: false,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        createdAt: days(1),
        updatedAt: days(1),
      },
      {
        id: "t8",
        subject: "Quick question about your stack",
        box: "screener",
        contactEmail: "unknown@coldmail.io",
        contactName: "Alex Pitch",
        messageIds: ["m8"],
        seen: false,
        replyLater: false,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        createdAt: hours(3),
        updatedAt: hours(3),
      },
      {
        id: "t9",
        subject: "SPEAKEASY conference follow-up",
        box: "lesbox",
        contactEmail: "vendor@booth.com",
        contactName: "Riley Booth",
        messageIds: ["m9"],
        seen: false,
        replyLater: false,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: true,
        accountMark: "work",
        createdAt: hours(4),
        updatedAt: hours(4),
      },
      {
        id: "t10",
        subject: "Benefits enrollment reminder",
        box: "lesbox",
        contactEmail: "hr@acme.io",
        contactName: "Acme HR",
        messageIds: ["m10"],
        seen: true,
        replyLater: false,
        setAside: false,
        bubbleUpAt: ahead(20),
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        accountMark: "work",
        createdAt: days(2),
        updatedAt: days(2),
      },
      {
        id: "t11",
        subject: "Launch checklist",
        customSubject: "Pricing page copy — blocking deploy",
        box: "lesbox",
        contactEmail: "priya@studio.dev",
        contactName: "Priya Nair",
        messageIds: ["m11"],
        seen: false,
        replyLater: true,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: ["col1"],
        workflowId: "wf1",
        workflowStageId: "ws1",
        notify: true,
        accountMark: "work",
        createdAt: hours(6),
        updatedAt: hours(6),
      },
      {
        id: "t12",
        subject: "Payment receipt for GitHub Team",
        box: "paper_trail",
        contactEmail: "billing@github.com",
        contactName: "GitHub",
        messageIds: ["m12"],
        seen: true,
        replyLater: false,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        createdAt: days(3),
        updatedAt: days(3),
      },
      {
        id: "t13",
        subject: "You have 14 unread messages",
        box: "lesbox",
        contactEmail: "notifications@slack.com",
        contactName: "Slack",
        messageIds: ["m13"],
        seen: false,
        replyLater: false,
        setAside: false,
        bundled: true,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        createdAt: hours(1),
        updatedAt: hours(1),
      },
      {
        id: "t14",
        subject: "Reminder: standup in 10 minutes",
        box: "lesbox",
        contactEmail: "notifications@slack.com",
        contactName: "Slack",
        messageIds: ["m14"],
        seen: false,
        replyLater: false,
        setAside: false,
        bundled: true,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        createdAt: hours(0.5),
        updatedAt: hours(0.5),
      },
      {
        id: "t15",
        subject: "You've been selected!!!",
        box: "screener",
        contactEmail: "spam@prize-now.biz",
        contactName: "Prize Desk",
        messageIds: ["m15"],
        seen: false,
        replyLater: false,
        setAside: false,
        bundled: false,
        unfollowed: false,
        stickyNotes: [],
        privateNotes: [],
        collectionIds: [],
        notify: false,
        createdAt: hours(0.2),
        updatedAt: hours(0.2),
      },
    ],
    contacts: [
      {
        id: "c1",
        email: "maya@design.co",
        name: "Maya Chen",
        status: "allowed",
        defaultBox: "lesbox",
        notes: "Met at Config 2024. Prefers async design feedback.",
        notify: true,
        avatarColor: "#5522FA",
        bundled: false,
      },
      {
        id: "c2",
        email: "sam@acme.io",
        name: "Sam Rivera",
        status: "allowed",
        defaultBox: "lesbox",
        notes: "VP Partnerships at Acme. Phone: 628-555-0199",
        notify: false,
        avatarColor: "#0074E4",
        bundled: false,
      },
      {
        id: "c3",
        email: "jordan@family.com",
        name: "Jordan Lee",
        status: "allowed",
        defaultBox: "lesbox",
        notes: "Cousin. Birthday: March 12.",
        notify: true,
        avatarColor: "#FF5A36",
        bundled: false,
      },
      {
        id: "c4",
        email: "newsletter@stratechery.com",
        name: "Stratechery",
        status: "allowed",
        defaultBox: "feed",
        notes: "",
        notify: false,
        avatarColor: "#1D2D35",
        bundled: false,
      },
      {
        id: "c5",
        email: "digest@morningbrew.com",
        name: "Morning Brew",
        status: "allowed",
        defaultBox: "feed",
        notes: "",
        notify: false,
        avatarColor: "#F5A623",
        bundled: false,
      },
      {
        id: "c6",
        email: "receipts@amazon.com",
        name: "Amazon",
        status: "allowed",
        defaultBox: "paper_trail",
        notes: "",
        notify: false,
        avatarColor: "#232F3E",
        bundled: false,
      },
      {
        id: "c7",
        email: "noreply@uber.com",
        name: "Uber",
        status: "allowed",
        defaultBox: "paper_trail",
        notes: "",
        notify: false,
        avatarColor: "#000000",
        bundled: false,
      },
      {
        id: "c8",
        email: "unknown@coldmail.io",
        name: "Alex Pitch",
        status: "pending",
        defaultBox: "lesbox",
        notes: "",
        notify: false,
        avatarColor: "#888888",
        bundled: false,
      },
      {
        id: "c9",
        email: "vendor@booth.com",
        name: "Riley Booth",
        status: "allowed",
        defaultBox: "lesbox",
        notes: "Speakeasy from SaaStr booth.",
        notify: true,
        avatarColor: "#00A86B",
        bundled: false,
      },
      {
        id: "c10",
        email: "notifications@slack.com",
        name: "Slack",
        status: "allowed",
        defaultBox: "lesbox",
        notes: "",
        notify: false,
        avatarColor: "#4A154B",
        bundled: true,
      },
      {
        id: "c11",
        email: "spam@prize-now.biz",
        name: "Prize Desk",
        status: "pending",
        defaultBox: "lesbox",
        notes: "",
        notify: false,
        avatarColor: "#CC0000",
        bundled: false,
      },
      {
        id: "c12",
        email: "priya@studio.dev",
        name: "Priya Nair",
        status: "allowed",
        defaultBox: "lesbox",
        notes: "PM on launch. Best reach before 11am PT.",
        notify: true,
        avatarColor: "#E91E8C",
        bundled: false,
      },
      {
        id: "c13",
        email: "billing@github.com",
        name: "GitHub",
        status: "allowed",
        defaultBox: "paper_trail",
        notes: "",
        notify: false,
        avatarColor: "#24292F",
        bundled: false,
      },
      {
        id: "c14",
        email: "hr@acme.io",
        name: "Acme HR",
        status: "allowed",
        defaultBox: "lesbox",
        notes: "",
        notify: false,
        avatarColor: "#336699",
        bundled: false,
      },
    ],
    collections: [
      {
        id: "col1",
        name: "Product Launch",
        threadIds: ["t1", "t2", "t11"],
        shared: true,
      },
    ],
    workflows: [
      {
        id: "wf1",
        name: "Deal pipeline",
        stages: [
          { id: "ws1", name: "Needs reply", color: "#FF5A36" },
          { id: "ws2", name: "In review", color: "#F5A623" },
          { id: "ws3", name: "Done", color: "#00A86B" },
        ],
      },
    ],
    snippets: [
      {
        id: "s1",
        name: "Thanks + will review",
        body: "Thanks for sending this over — I'll review and get back to you by end of day.",
      },
      {
        id: "s2",
        name: "Meeting confirmed",
        body: "Confirmed! Looking forward to it. I'll send a calendar invite shortly.",
      },
      {
        id: "s3",
        name: "Out of office short",
        body: "I'm away with limited email access. I'll reply when I'm back.",
      },
    ],
    emailTemplates: [
      {
        id: "et1",
        name: "Intro / hello",
        subject: "Quick hello",
        body: "Hi,\n\nHope you're doing well. I wanted to reach out about…\n\nBest,",
      },
      {
        id: "et2",
        name: "Follow-up",
        subject: "Following up",
        body: "Hi,\n\nJust following up on my note below. Happy to jump on a quick call if that's easier.\n\nThanks,",
      },
      {
        id: "et3",
        name: "Meeting request",
        subject: "Meeting this week?",
        body: "Hi,\n\nWould you have 20–30 minutes this week to connect? I'm free most afternoons.\n\nLooking forward to it,",
      },
      {
        id: "et4",
        name: "Thank you",
        subject: "Thank you",
        body: "Hi,\n\nThank you — I really appreciate your help with this.\n\nBest,",
      },
      {
        id: "et5",
        name: "Proposal reply",
        subject: "Re: proposal",
        body: "Hi,\n\nThanks for the proposal. I've reviewed it and have a few thoughts:\n\n1. \n2. \n3. \n\nHappy to discuss live.",
      },
    ],
    signatures: [
      {
        id: "sig1",
        name: "Personal",
        html: "<p>Best,<br/><strong>You</strong><br/>Les Mail</p>",
        isDefault: true,
      },
      {
        id: "sig2",
        name: "Work",
        html: "<p>Thanks,<br/><strong>You</strong><br/>Product · Acme</p>",
        isDefault: false,
      },
    ],
    clips: [
      {
        id: "cl1",
        text: "415-555-0142",
        sourceThreadId: "t11",
        sourceSubject: "Launch checklist",
        createdAt: hours(5),
      },
      {
        id: "cl2",
        text: "Order #112-88421",
        sourceThreadId: "t6",
        sourceSubject: "Your order has shipped",
        createdAt: hours(11),
      },
    ],
    calendars: [
      { id: "cal1", name: "Personal", color: "#5522FA", visible: true },
      { id: "cal2", name: "Work", color: "#0074E4", visible: true },
      { id: "cal3", name: "Family", color: "#FF5A36", visible: true },
    ],
    events: [
      {
        id: "e1",
        title: "Design review",
        start: ahead(46),
        end: ahead(47),
        calendarId: "cal2",
        location: "Zoom",
        meetingUrl: "https://zoom.us/j/123456789",
        fromThreadId: "t1",
        reminderMinutes: [15, 60],
      },
      {
        id: "e2",
        title: "Dinner with Jordan",
        start: aheadDays(2),
        end: aheadDays(2),
        allDay: false,
        calendarId: "cal3",
        location: "5th Street Bistro",
        notes: "Reservation for 7pm",
        countdown: true,
        reminderMinutes: [60],
      },
      {
        id: "e3",
        title: "Acme kickoff",
        start: aheadDays(3),
        end: aheadDays(3),
        calendarId: "cal2",
        meetingUrl: "https://meet.google.com/abc-defg-hij",
        fromThreadId: "t2",
        countdown: true,
        reminderMinutes: [15],
      },
      {
        id: "e4",
        title: "Focus block",
        start: ahead(4),
        end: ahead(6),
        calendarId: "cal1",
        notes: "Deep work — no meetings",
      },
      {
        id: "e5",
        title: "Standup",
        start: ahead(0.2),
        end: ahead(0.5),
        calendarId: "cal2",
        meetingUrl: "https://zoom.us/j/standup",
        reminderMinutes: [5],
      },
      {
        id: "e6",
        title: "Vacation — Hawaii",
        start: aheadDays(30),
        end: aheadDays(37),
        allDay: true,
        calendarId: "cal1",
        countdown: true,
      },
    ],
    habits: [
      { id: "h1", name: "Exercise", color: "#00A86B", completedDates: [] },
      { id: "h2", name: "Read 20 min", color: "#5522FA", completedDates: [] },
      { id: "h3", name: "Inbox clear", color: "#0074E4", completedDates: [] },
    ],
    journal: [
      {
        id: "j1",
        date: new Date().toISOString().slice(0, 10),
        body: "Shipping the HEY clone demo today. Keep LesBox clean — Reply Later for anything that needs depth.",
      },
    ],
    dayLabels: [
      { id: "dl1", date: new Date(now + 2 * 86400_000).toISOString().slice(0, 10), label: "Family dinner night" },
      { id: "dl2", date: new Date(now + 3 * 86400_000).toISOString().slice(0, 10), label: "Acme week begins" },
    ],
    sometimeTasks: [
      { id: "st1", text: "Renew domain + SSL", done: false, createdAt: days(2) },
      { id: "st2", text: "Book dentist", done: false, createdAt: days(5) },
      { id: "st3", text: "Send thank-you note to Maya", done: true, createdAt: days(1) },
    ],
    settings: {
      displayName: "You",
      email: "you@lesmail.local",
      workEmail: "you@work.local",
      speakeasyCode: "SPEAKEASY",
      autoresponderOn: false,
      autoresponderMessage: "I'm away until next week. I'll get back to you when I return.",
      spamCorps: true,
      coverArt: "calendar",
      timezone: "America/Los_Angeles",
      secondaryTimezone: "America/New_York",
      twoFactorEnabled: true,
      linkedAccounts: true,
      wallpaper: "rotate",
      wallpaperRotateMinutes: 8,
      autoFetchMinutes: 2,
      requestReadReceiptsByDefault: true,
      defaultSignatureId: "sig1",
    },
  };
}
