/** Common provider presets for Les Mail */
const PRESETS = {
  gmail: {
    id: "gmail",
    label: "Gmail / Google Workspace",
    imapHost: "imap.gmail.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.gmail.com",
    smtpPort: 465,
    smtpSecure: true,
    needsAppPassword: true,
    appPasswordUrl: "https://myaccount.google.com/apppasswords",
    hint: "Gmail needs an App Password (not your normal login). Click “Open App Password page”, create one named Les Mail, then paste it here.",
  },
  yahoo: {
    id: "yahoo",
    label: "Yahoo Mail",
    imapHost: "imap.mail.yahoo.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.mail.yahoo.com",
    smtpPort: 465,
    smtpSecure: true,
    needsAppPassword: true,
    appPasswordUrl: "https://login.yahoo.com/account/security/app-passwords-list.html",
    hint: "Yahoo needs an App Password. Click “Open App Password page”, generate one, then paste it here.",
  },
  aol: {
    id: "aol",
    label: "AOL Mail",
    imapHost: "imap.aol.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.aol.com",
    smtpPort: 465,
    smtpSecure: true,
    needsAppPassword: true,
    appPasswordUrl: "https://login.aol.com/account/security/app-passwords",
    hint: "AOL needs an App Password. Click “Open App Password page”, generate one, then paste it here.",
  },
  outlook: {
    id: "outlook",
    label: "Outlook / Microsoft 365 / Hotmail",
    imapHost: "outlook.office365.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.office365.com",
    smtpPort: 587,
    smtpSecure: false,
    needsAppPassword: true,
    appPasswordUrl: "https://account.live.com/proofs/AppPassword",
    hint: "Personal Microsoft accounts may need an app password. Work/school orgs may require admin IMAP access.",
  },
  icloud: {
    id: "icloud",
    label: "iCloud Mail",
    imapHost: "imap.mail.me.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.mail.me.com",
    smtpPort: 587,
    smtpSecure: false,
    needsAppPassword: true,
    appPasswordUrl: "https://appleid.apple.com/account/manage",
    hint: "Create an app-specific password at appleid.apple.com (Sign-In and Security → App-Specific Passwords).",
  },
  fastmail: {
    id: "fastmail",
    label: "Fastmail",
    imapHost: "imap.fastmail.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.fastmail.com",
    smtpPort: 465,
    smtpSecure: true,
    needsAppPassword: true,
    appPasswordUrl: "https://app.fastmail.com/settings/security/app-passwords",
    hint: "Use a Fastmail app password from Settings → Privacy & Security.",
  },
  stackmail: {
    id: "stackmail",
    label: "Stackmail / 20i (hosted domains)",
    imapHost: "imap.stackmail.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.stackmail.com",
    smtpPort: 465,
    smtpSecure: true,
    needsAppPassword: false,
    appPasswordUrl: "",
    hint: "For domains on 20i/Stackmail. Username = full email. Use your mailbox password from the hosting panel.",
  },
  custom: {
    id: "custom",
    label: "Custom IMAP / SMTP",
    imapHost: "",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "",
    smtpPort: 465,
    smtpSecure: true,
    needsAppPassword: false,
    appPasswordUrl: "",
    hint: "Enter your provider’s IMAP/SMTP hosts — or use Auto-detect. Switching to Custom keeps hosts you already typed.",
  },
};

module.exports = { PRESETS };
