/** Common provider presets for Les Mail */
const PRESETS = {
  gmail: {
    id: "gmail",
    label: "Gmail / Google Workspace",
    imapHost: "imap.gmail.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.gmail.com",
    smtpPort: 465,
    smtpSecure: true,
    hint: "Use an App Password if 2FA is on (Google Account → Security → App passwords).",
  },
  outlook: {
    id: "outlook",
    label: "Outlook / Microsoft 365 / Hotmail",
    imapHost: "outlook.office365.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.office365.com",
    smtpPort: 587,
    smtpSecure: false,
    hint: "May require an app password or OAuth depending on your org.",
  },
  icloud: {
    id: "icloud",
    label: "iCloud Mail",
    imapHost: "imap.mail.me.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.mail.me.com",
    smtpPort: 587,
    smtpSecure: false,
    hint: "Generate an app-specific password at appleid.apple.com.",
  },
  yahoo: {
    id: "yahoo",
    label: "Yahoo Mail",
    imapHost: "imap.mail.yahoo.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.mail.yahoo.com",
    smtpPort: 465,
    smtpSecure: true,
    hint: "Generate an app password in Yahoo Account Security.",
  },
  fastmail: {
    id: "fastmail",
    label: "Fastmail",
    imapHost: "imap.fastmail.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.fastmail.com",
    smtpPort: 465,
    smtpSecure: true,
    hint: "Use a Fastmail app password.",
  },
  stackmail: {
    id: "stackmail",
    label: "Stackmail / 20i (hosted domains)",
    imapHost: "imap.stackmail.com",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "smtp.stackmail.com",
    smtpPort: 465,
    smtpSecure: true,
    hint: "For domains on 20i/Stackmail (e.g. many custom business domains). Username = full email.",
  },
  custom: {
    id: "custom",
    label: "Custom IMAP / SMTP",
    imapHost: "",
    imapPort: 993,
    imapSecure: true,
    smtpHost: "",
    smtpPort: 465,
    smtpSecure: true,
    hint: "Enter your provider’s IMAP/SMTP hosts — or use Auto-detect from your email address. Switching to Custom keeps hosts you already typed.",
  },
};

module.exports = { PRESETS };
